-- MySQL Script generated by MySQL Workbench
-- Wed Jun 29 15:31:34 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ColorCoded
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ColorCoded` ;

-- -----------------------------------------------------
-- Schema ColorCoded
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ColorCoded` DEFAULT CHARACTER SET utf8 ;
USE `ColorCoded` ;

-- -----------------------------------------------------
-- Table `ColorCoded`.`Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ColorCoded`.`Users` ;

CREATE TABLE IF NOT EXISTS `ColorCoded`.`Users` (
  `UserID` INT NOT NULL AUTO_INCREMENT,
  `UserName` VARCHAR(45) NULL,
  `UserPw` VARCHAR(45) NULL,
  `AcctCreated` DATE NULL,
  `LastLogin` DATE NULL,
  PRIMARY KEY (`UserID`),
  UNIQUE INDEX `UserName_UNIQUE` (`UserName` ASC) INVISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ColorCoded`.`Palette`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ColorCoded`.`Palette` ;

CREATE TABLE IF NOT EXISTS `ColorCoded`.`Palette` (
  `PaletteID` INT NOT NULL,
  `PaletteName` VARCHAR(45) NULL,
  `Owner_UserID` INT NOT NULL,
  PRIMARY KEY (`PaletteID`),
  INDEX `fk_Palette_Users_idx` (`Owner_UserID` ASC) VISIBLE,
  CONSTRAINT `fk_Palette_Users1`
    FOREIGN KEY (`Owner_UserID`)
    REFERENCES `ColorCoded`.`Users` (`UserID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ColorCoded`.`Color`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ColorCoded`.`Color` ;

CREATE TABLE IF NOT EXISTS `ColorCoded`.`Color` (
  `ColorID` INT NOT NULL,
  `R` INT NULL,
  `G` INT NULL,
  `B` INT NULL,
  PRIMARY KEY (`ColorID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ColorCoded`.`PColor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ColorCoded`.`PColor` ;

CREATE TABLE IF NOT EXISTS `ColorCoded`.`PColor` (
  `Color_ColorID` INT NOT NULL,
  `Palette_PaletteID` INT NOT NULL,
  PRIMARY KEY (`Color_ColorID`, `Palette_PaletteID`),
  INDEX `fk_Palette_PColor_idx` (`Palette_PaletteID` ASC) VISIBLE,
  INDEX `fk_Color_PColor_idx` (`Color_ColorID` ASC) VISIBLE,
  CONSTRAINT `fk_Color_has_Palette_Color`
    FOREIGN KEY (`Color_ColorID`)
    REFERENCES `ColorCoded`.`Color` (`ColorID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Color_has_Palette_Palette1`
    FOREIGN KEY (`Palette_PaletteID`)
    REFERENCES `ColorCoded`.`Palette` (`PaletteID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
